name: Contributors

on:
  push:
    branches: ["main"]

jobs:
  contributor_report:
    name: contributor report
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Set dates
        shell: bash
        run: |
          start_date=2022-01-01
          end_date=$(date +%Y-%m-%d)
          echo "START_DATE=$start_date" >> "$GITHUB_ENV"
          echo "END_DATE=$end_date" >> "$GITHUB_ENV"

      - name: Contributors Action
        uses: github/contributors@v1.4.3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: ${{ github.repository }}

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Contributor report
          token: ${{ secrets.GH_TOKEN }}
          content-filepath: ./contributors.md
          assignees: ${{ github.repository_owner }}
          labels: |
            report
            automated issue
