name: CMake

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Contributors Action
        uses: github/contributors@v1.4.3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Contributor report
          token: ${{ secrets.GH_TOKEN }}
          content-filepath: ./CONTRIBUTORS.md
